import React from 'react'

const FAQ = () => {
  return (
    <div>FAQ
      Gentleman, you are gathered here because one of our young chief scientists disappeared. The last trace we have of him was at 1635hrs three days ago. We do not know how this happened, or who is responsible, and we are assessing all possible angles. The scientist's name is Ralph Sosera. A child protege who was identified by the ARS at the age of 16 right before his priming initiation about 80 years ago. He is also the one who played a key role in the development of our Relationship Control Program which has given us incredible results in getting people to cooperate and work more for the system. Everything you need to know will be there in the files sent to you. Again, I will emphasize that you respect your responsibility levels, the information given to you is unique to your capacity, don't push for access, and work with what you have been given.
Of interest are three specific details. Sosera was a single widower with religious parents who went under the protection of the Church after they faltered and their Responsibility Credit scores fell. The second is that Sosera has been displaying anomalous behaviour with slight but negligible deviations from his expected benchmark. His wife died during a toxic water contamination disaster and that's also when his deviations began. Our surveillance reported that his parents reached out to him in an encrypted message and we don't know what they talked about, but we are working on the theory that they radicalized him If that's the case then he is likely to try and cross the border in The Rabble and seek asylum. Gentlemen we will not let that happen.

Gentleman, you are gathered here because one of our young chief scientists disappeared. The last trace we have of him was at 1635hrs three days ago. We do not know how this happened, or who is responsible, and we are assessing all possible angles. The scientist's name is Ralph Sosera. A child protege who was identified by the ARS at the age of 16 right before his priming initiation about 80 years ago. He is also the one who played a key role in the development of our Relationship Control Program which has given us incredible results in getting people to cooperate and work more for the system. Everything you need to know will be there in the files sent to you. Again, I will emphasize that you respect your responsibility levels, the information given to you is unique to your capacity, don't push for access, and work with what you have been given.
Of interest are three specific details. Sosera was a single widower with religious parents who went under the protection of the Church after they faltered and their Responsibility Credit scores fell. The second is that Sosera has been displaying anomalous behaviour with slight but negligible deviations from his expected benchmark. His wife died during a toxic water contamination disaster and that's also when his deviations began. Our surveillance reported that his parents reached out to him in an encrypted message and we don't know what they talked about, but we are working on the theory that they radicalized him If that's the case then he is likely to try and cross the border in The Rabble and seek asylum. Gentlemen we will not let that happen.
Gentleman, you are gathered here because one of our young chief scientists disappeared. The last trace we have of him was at 1635hrs three days ago. We do not know how this happened, or who is responsible, and we are assessing all possible angles. The scientist's name is Ralph Sosera. A child protege who was identified by the ARS at the age of 16 right before his priming initiation about 80 years ago. He is also the one who played a key role in the development of our Relationship Control Program which has given us incredible results in getting people to cooperate and work more for the system. Everything you need to know will be there in the files sent to you. Again, I will emphasize that you respect your responsibility levels, the information given to you is unique to your capacity, don't push for access, and work with what you have been given.
Of interest are three specific details. Sosera was a single widower with religious parents who went under the protection of the Church after they faltered and their Responsibility Credit scores fell. The second is that Sosera has been displaying anomalous behaviour with slight but negligible deviations from his expected benchmark. His wife died during a toxic water contamination disaster and that's also when his deviations began. Our surveillance reported that his parents reached out to him in an encrypted message and we don't know what they talked about, but we are working on the theory that they radicalized him If that's the case then he is likely to try and cross the border in The Rabble and seek asylum. Gentlemen we will not let that happen.
Gentleman, you are gathered here because one of our young chief scientists disappeared. The last trace we have of him was at 1635hrs three days ago. We do not know how this happened, or who is responsible, and we are assessing all possible angles. The scientist's name is Ralph Sosera. A child protege who was identified by the ARS at the age of 16 right before his priming initiation about 80 years ago. He is also the one who played a key role in the development of our Relationship Control Program which has given us incredible results in getting people to cooperate and work more for the system. Everything you need to know will be there in the files sent to you. Again, I will emphasize that you respect your responsibility levels, the information given to you is unique to your capacity, don't push for access, and work with what you have been given.
Of interest are three specific details. Sosera was a single widower with religious parents who went under the protection of the Church after they faltered and their Responsibility Credit scores fell. The second is that Sosera has been displaying anomalous behaviour with slight but negligible deviations from his expected benchmark. His wife died during a toxic water contamination disaster and that's also when his deviations began. Our surveillance reported that his parents reached out to him in an encrypted message and we don't know what they talked about, but we are working on the theory that they radicalized him If that's the case then he is likely to try and cross the border in The Rabble and seek asylum. Gentlemen we will not let that happen.
Gentleman, you are gathered here because one of our young chief scientists disappeared. The last trace we have of him was at 1635hrs three days ago. We do not know how this happened, or who is responsible, and we are assessing all possible angles. The scientist's name is Ralph Sosera. A child protege who was identified by the ARS at the age of 16 right before his priming initiation about 80 years ago. He is also the one who played a key role in the development of our Relationship Control Program which has given us incredible results in getting people to cooperate and work more for the system. Everything you need to know will be there in the files sent to you. Again, I will emphasize that you respect your responsibility levels, the information given to you is unique to your capacity, don't push for access, and work with what you have been given.
Of interest are three specific details. Sosera was a single widower with religious parents who went under the protection of the Church after they faltered and their Responsibility Credit scores fell. The second is that Sosera has been displaying anomalous behaviour with slight but negligible deviations from his expected benchmark. His wife died during a toxic water contamination disaster and that's also when his deviations began. Our surveillance reported that his parents reached out to him in an encrypted message and we don't know what they talked about, but we are working on the theory that they radicalized him If that's the case then he is likely to try and cross the border in The Rabble and seek asylum. Gentlemen we will not let that happen.

    </div>
  )
}

export default FAQ